### ISSUE TITLE
No Matching Version while updating Angular App

### ISSUE THREAD

**Issue by ImeriAlmir** [isaacs/jackspeak#10]
I wanted to update my Angular using `ng update @angular/core @angular/cli ` command
when I execute the command I get the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for jackspeak@^2.3.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

when I try to do `npm install jackspeak@2.3.5` I get the same error but when I do just `npm install jackspeak` I get no error. But the installed Version is still 2.3.3. I also tried to change the version in the package.json, the error also appears there.

I am using Node Version: `16.14.2` and I want to update my Angular App from `Version 15 ` to `Version 16`

**Comment by Stargator** [comment]
The same is happening to me when I try to install any version of @angular/cli

**Comment by Stargator** [comment]
I was able to resolve my issue by setting NPM's prefer-offline config to false.
