### ISSUE TITLE
The dependencies of the @isaacs/cliui package cannot be recognized by cnpm

### ISSUE THREAD

**Issue by yehuozhili** [isaacs/jackspeak#11]
cnpm didn'n understand npm:string-width like this . we use private npm like cnpm to build our app

**Comment by yehuozhili** [comment]
https://github.com/cnpm/cnpm

**Comment by garronej** [comment]
Hello,

It's also a problem with Storybook: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092

**Comment by isaacs** [comment]
Sorry, I don't support package managers that don't support package aliases. You can install with regular npm and then vendor it or check it in or whatever you want to do.
