### ISSUE TITLE
Node 14 support broken due to nullish coalescing operator

### ISSUE THREAD

**Issue by SeinopSys** [isaacs/jackspeak#12]
Trying to run another package that depends on this one (namely [`npx glob`](https://github.com/isaacs/node-glob/issues/593)) using Node 14.20.1 results in the following:

```
npx: installed 41 in 2.817s
file:///Users/seinopsys/.npm/_npx/4474/lib/node_modules/glob/node_modules/jackspeak/dist/esm/index.js:496
                cause ??= { name: field, found: value };
                      ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
```

The `??=` operator is only supported from Node version 15.14.0 onwards ([source](https://node.green/#ES2021-features-Logical-Assignment-----basic-support)).

The `engines` field in both `package.json` files list node 14.20.1 as part of the allowed version range, but the are no checks to validate this.

I would like to suggest adding validations for all supported Node versions or dropping support for these older versions via removing them from the `engines` constraint if they are no longer actively validated.

**Comment by isaacs** [comment]
https://nodejs.org/en/blog/announcements/nodejs16-eol/

16 been EOL for 10 months. 14 has been EOL for over a year. Pin your deps and only upgrade carefully if you are using EOL platform versions.
