### ISSUE TITLE
Version 3.4.1 drops Node 14 and 16 support

### ISSUE THREAD

**Issue by Lms24** [isaacs/jackspeak#13]
Commit https://github.com/isaacs/jackspeak/commit/0534792742b9ae05ee7219cf92c369c18afc4a2e introduced a min Node version bump to Node 18, meaning support for 14 and 16 was dropped in a minor release. This just broke our CI.

For the moment we can work around this with a dependency resolution override but I'd ask to only drop Node version support in a major version. I'm sure we're not the only ones affected by this. More specifically, folks running Remix v1 on Node 16 are probably gonna run into this.

**Comment by isaacs** [comment]
https://nodejs.org/en/blog/announcements/nodejs16-eol/

It's been EOL for 10 months. Pin your deps and only upgrade carefully if you are using EOL platform versions.

**Comment by Lms24** [comment]
If we (Sentry) did this with our SDKs, people would flood us with hate on twitter. This is a breaking change, please reconsider. What's the harm in cutting a major?

**Comment by isaacs** [comment]
@Lms24 Sentry is a company with paying customers. I'm just some person on the internet doing this for free. Surely you see there is a wildly different level of reasonable entitlement and expectation of support.

I have elaborated on twitter, in github issues, and elsewhere, the harm in "just cutting a major" for every engine drop. 

> This is a breaking change

It really shouldn't be, as the API hasn't changed. SemVer is intended to be about the API, not about supported platforms it runs on.

However, as it turns out, there is a bug in npm (which I had thought was fixed years ago, but the PR wasn't landed until just the other day) which prevented npm from properly filtering out engine mismatches. Moving forward, in the latest versions of my packages that require newer node versions, engine dropping will be considered a patch change, because it will not require any work on the part of consumers to upgrade, as the engine mismatch will be filtered out by default just like a semver major would.

There's already a v3 out now with no engines restrictions at all. Good luck, have fun. It's the last update v3 of this library will ever get. Cutting a major means support is over for any previous majors, unless someone wants to pay for my time to do so.

**Comment by Lms24** [comment]
It wasn't my intention to come across as being entitled to a certain level of service for OSS. I do recognize and appreciate that you're doing this for free (side note: Sentry [sponsors](https://thanks.dev/d/gh/getsentry/dependencies) you, just like most OSS maintainer we use libraries from, specifically for `jackspeak`, albeit in a (IMHO) small manner). I apologize for conveing a different message in my previous replies.
 
Secondly, great to hear that NPM now correctly respects `engine`! Thanks for pointing this out; I had no idea that it is due to a bug and not by design. Though I wonder if other package managers respect this, too. 

My main concern is that dropping Node version support (regardless if EOL or not) in a patch _does_ cause a signficant level of problems for library consumers or, as in our case, if the dependency in question is a transitive dependency that's badly/not pinnend by the primary package. In most cases this comes down to user error (as you described) but regardless, it makes people invest time into fixing things they didn't plan for. 

Sure, you can argue about where to draw the line with semver. By the book definition of it you're probably right. Still, I personally would include Node version support, as many other package maintainers do. Mainly because the "[prioritze convenience over correctness](https://develop.sentry.dev/sdk/philosophy/#prioritize-customer-convenience-over-correctness)" philosophy really resonates with me and the experiences I've made maintaining widely used NPM packages. 

As to our concrete case, we tmp-fixed it on our end after figuring out the correct package resolution overrides. Long-term, we'll probably restructure the test applications that failed for us when the package update was released to avoid problems like these. For the record, in our case, we don't _use_ EOL Node versions actively but we do guarantee support for Node 14+ of the Sentry SDKs because our philosophy generally is to [support things as long as reasonably possible](https://develop.sentry.dev/sdk/philosophy/#compatibility-is-king). This forces us to test on EOL versions. In this particular test, we automated Node version switching (via GH matrix) in the same test app, making a lock file problematic. Which is why the error occured. 

To end things on a peaceful note, thanks for responding and outlining your train of thought (also read and responded to your twitter thread). We may still disagree here but I respect your decision and I learned a lot through it :)

**Comment by isaacs** [comment]
> My main concern is that dropping Node version support (regardless if EOL or not) in a patch does cause a signficant level of problems for library consumers or, as in our case, if the dependency in question is a transitive dependency that's badly/not pinnend by the primary package.

Once that npm-pick-manifest patch is in widespread usage (as I mistakenly thought it was already!), it will no longer be such an issue. For now, I've changed all the node <20 drops to be on semver major bumps, and we can enjoy lots of excessive duplication instead, lolsob

The Sentry page you linked to twice in your message contains the word "customer" 22 times. That is imo extremely telling as to why we should be expected to have _wildly_ different support obligations. Simply put, _you have customers_, and _I do not_. Sentry (or any company) is not anyone's "customer" by virtue of using their open source. There is no quid-pro-quo relationship, no support engagement, no reasonable expectation of reliability or fitness. That's _all on you_ to evaluate and maintain, and anything you get from an OSS maintainer is a gift provided as-is. That is part of the job of "picking code out of a dumpster, stitching it together, and selling the result". But you're not the dumpster's customer, and it's not your supplier.

> Sentry [sponsors](https://thanks.dev/d/gh/getsentry/dependencies) you, just like most OSS maintainer we use libraries from, specifically for jackspeak, albeit in a (IMHO) small manner

True, Sentry pays me around $15 per month on average, split across a few different GH orgs and my personal account.

I'm not trying to be ungrateful, but let's not kid ourselves, this is not just your humble opinion that it's small; I could literally make more money begging on the side of the road than I do on open source. So, yes, I am actually doing this for free. The donations are a token performance. I don't mean that in a disparaging way. I do appreciate the sentiment; but that's all it is, really. If Sentry paid anything near the value they receive, let alone enough to have a meaningful impact on the financial viability of open source, they'd be at a severe disadvantage relative to their competitors in the market who _don't_ pay. This is a bigger problem than one company can meaningfully affect.

What we need is widespread systemic change, which will only happen when those of us in the community of OSS producers collectively withhold our labor from all commercial actors unless they pay a fair rate for access to it, based on the value received.

I realize that my stance on this is unusually forceful and may even seem hostile or angry. I'm really not heated about it! I do love open source, I love giving away code, I even really like Sentry, y'all are great folks, and the "be the change you wish to see" approach is beautiful. Even without any financial recognition, creation is its own reward.

But having seen so many absolutely amazing genius creators burn out and disappear, and the toll it takes on their mental, physical, social, emotional, and financial health, I have come to realize that the only reason I've been _able_ to stay at this so long is that I have such a hard boundary here, and take that all-caps portion of the license so seriously.
