### ISSUE TITLE
`tshy` dependency introduced in 2.3.4 patch causes node engine incompatibility

### ISSUE THREAD

**Issue by Ben-Kincaid** [isaacs/jackspeak#9]
The new `tshy` dependency that was introduced in 2.3.4 enforces a [different range for it's node version](https://github.com/isaacs/tshy/blob/main/package.json#L37C12-L37C53) than what jackspeak defines (`>=14`), breaking dependency installation for existing lerna installations that are not within the range specified by `tshy`.

Is this something that could be instead defined as a dev dependency?

**Comment by isaacs** [comment]
It's been a devDep for a while now.
